dist: xenial  # required for Python >= 3.7
language: python
python: 3.7

install: pip install pytest-mypy codecov pytest-cov

script: pytest --mypy --doctest-modules --ignore python/easy/_rest.py --cov-report term --cov=.

after_success: codecov
